<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>LinkerScript</string>
	<key>scopeName</key>
	<string>source.ld</string>
	<key>fileTypes</key>
	<array>
		<string>ld</string>
	</array>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#simple_commands</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#assignments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#sections</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#memory</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#phdrs</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#version</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#expressions</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>name</key>
			<string>comment.block.ld</string>
			<key>begin</key>
			<string>/\*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.ld</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.end.ld</string>
				</dict>
			</dict>
		</dict>
		<key>simple_commands</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>support.function.builtin.ld</string>
					<key>match</key>
					<string>(?x) \b(?: ENTRY )\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.builtin.ld</string>
					<key>match</key>
					<string>(?x) \b(?: INCLUDE |INPUT |GROUP |OUTPUT |SEARCH_DIR |STARTUP )\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.builtin.ld</string>
					<key>match</key>
					<string>(?x) \b(?: OUTPUT_FORMAT |TARGET )\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.builtin.ld</string>
					<key>match</key>
					<string>(?x) \b(?: ASSERT |EXTERN |FORCE_COMMON_ALLOCATION |INHIBIT_COMMON_ALLOCATION |NOCROSSREFS |OUTPUT_ARCH )\b</string>
				</dict>
			</array>
		</dict>
		<key>assignments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operand.ld</string>
					<key>match</key>
					<string>=|\+=|-=|\*=|/=|&lt;&lt;=|&gt;&gt;=|&amp;=|\|=</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.builtin.ld</string>
					<key>match</key>
					<string>(?x) \b(?: PROVIDE |HIDDEN |PROVIDE_HIDDEN |SEGMENT_START )\b</string>
				</dict>
			</array>
		</dict>
		<key>sections</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>support.function.builtin.ld</string>
					<key>match</key>
					<string>(?x) \b(?:SECTIONS)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>section.input.ld</string>
					<key>match</key>
					<string>(?x) (\S+)((?:\s*\(\s*)(((\.[\.\*\w]+)(?:\s*))+)(?:\s*\)))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.builtin.ld</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.ld</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>section.output.prepart.ld</string>
					<key>match</key>
					<string>(?mx) (\B\.[\.\*\w]+\b)(?:\s*)(\w*)(?:\s*)((\(\s*[\w]*\s*\))?)(?:\s*)(\:)(?:\s*)((AT)?)(?:\s*\(?)(\w*)(?:\s*\)?)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.ld</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.ld</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.control.ld</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.operand.ld</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>support.function.builtin.ld</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.ld</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>section.output.postpart.ld</string>
					<key>match</key>
					<string>(?:\}\s*)((\&gt;)(\s*\w*)?)(?:\s*)((AT)(?:\s*)(\&gt;)(?:\s*)(\w*))?(?:\s*)(((\:\w*)(?:\s*))*)(((\=)(?:\s*)(\w*))?)</string>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operand.ld</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.ld</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>support.function.builtin.ld</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>keyword.operand.ld</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>variable.other.ld</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>keyword.control.ld</string>
						</dict>
						<key>13</key>
						<dict>
							<key>name</key>
							<string>keyword.operand.ld</string>
						</dict>
						<key>14</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.ld</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.builtin.ld</string>
					<key>match</key>
					<string>(?x) \b(?: EXCLUDE_FILE |CREATE_OBJECT_SYMBOLS |CONSTRUCTORS )\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>datatypes.ld</string>
					<key>match</key>
					<string>(?x) (BYTE|SHORT|LONG|QUAD|SQUAD)(?:\s*\(\s*)([^\(\)]*)(?:\s*\))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.ld</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.ld</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>section.discard.ld</string>
					<key>match</key>
					<string>(/DISCARD/)(?:\s*)(\:)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.ld</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operand.ld</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>memory</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>support.function.builtin.ld</string>
					<key>match</key>
					<string>(?x) \b(?:MEMORY)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>memory.config.ld</string>
					<key>match</key>
					<string>(\S*)(?:\s*\(\s*)((R|r|W|w|X|x|A|a|I|i|L|l|\!)+)(?:\s*\)\s*)(\:)((?:\s*)(ORIGIN|org|o|LENGTH|len|l)(?:\s*)(\=)(?:\s*)(\w*)(,?))((?:\s*)(ORIGIN|org|o|LENGTH|len|l)(?:\s*)(\=)(?:\s*)(\w*))</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.ld</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.ld</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.operand.ld</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>support.variable.ld</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>keyword.operand.ld</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.ld</string>
						</dict>
						<key>11</key>
						<dict>
							<key>name</key>
							<string>support.variable.ld</string>
						</dict>
						<key>12</key>
						<dict>
							<key>name</key>
							<string>keyword.operand.ld</string>
						</dict>
						<key>13</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.ld</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.builtin.ld</string>
					<key>match</key>
					<string>(?x) \b(?: LENGTH |len |l |ORIGIN |org |o )\b</string>
				</dict>
			</array>
		</dict>
		<key>phdrs</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>support.function.builtin.ld</string>
					<key>match</key>
					<string>(?x) \b(?:PHDRS)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>phdrs.config.ld</string>
					<key>match</key>
					<string>(\w*)(?:\s*)(PT_NULL|PT_LOAD|PT_DYNAMIC|PT_INTERP|PT_NOTE|PT_SHLIB|PT_PHDR)(?:\s*)((FILEHDR)?)(?:\s*)((PHDRS)?)(?:\s*)((((AT)?)(?:\s*\(\s*)(\w*)(?:\s*\)\s*))?)((((FLAGS)?)(?:\s*\(\s*)(\w*)(?:\s*\)\s*))?)(\;)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.ld</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.ld</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.control.ld</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>keyword.control.ld</string>
						</dict>
						<key>10</key>
						<dict>
							<key>name</key>
							<string>support.function.builtin.ld</string>
						</dict>
						<key>11</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.ld</string>
						</dict>
						<key>15</key>
						<dict>
							<key>name</key>
							<string>support.function.builtin.ld</string>
						</dict>
						<key>16</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.ld</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>version</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>support.function.builtin.ld</string>
					<key>match</key>
					<string>(?x) \b(?:VERSION)\b</string>
				</dict>
			</array>
		</dict>
		<key>expressions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>expression.ld</string>
					<key>match</key>
					<string>(\w*)(?:\s*)(=|\+=|-=|\*=|/=|&lt;&lt;=|&gt;&gt;=|&amp;=|\|=)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.ld</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operand.ld</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.ld</string>
					<key>match</key>
					<string>(?x) \b(?:(MAXPAGESIZE)|(COMMONPAGESIZE))\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.other.ld</string>
					<key>match</key>
					<string>\.</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operand.ld</string>
					<key>match</key>
					<string>!|-|~</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operand.ld</string>
					<key>match</key>
					<string>\*|/|%</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operand.ld</string>
					<key>match</key>
					<string>\+|\-</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operand.ld</string>
					<key>match</key>
					<string>&lt;&lt;|&gt;&gt;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operand.ld</string>
					<key>match</key>
					<string>==|!=|&gt;|&lt;|&gt;=|&lt;=</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operand.ld</string>
					<key>match</key>
					<string>&amp;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operand.ld</string>
					<key>match</key>
					<string>\|</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operand.ld</string>
					<key>match</key>
					<string>&amp;&amp;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operand.ld</string>
					<key>match</key>
					<string>\|\|</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operand.ld</string>
					<key>match</key>
					<string>\?|\:</string>
				</dict>
				<dict>
					<key>name</key>
					<string>support.function.builtin.ld</string>
					<key>match</key>
					<string>(?x) \b(?: ABSOLUTE |ADDR |ALIGN |BLOCK |DATA_SEGMENT_ALIGN |DATA_SEGMENT_END |DEFINED |LOADADDR |MAX |MIN |NEXT |SIZEOF |SIZEOF_HEADERS |sizeof_headers )\b</string>
				</dict>
			</array>
		</dict>
	</dict>
</dict>
</plist>
